### ISSUE TITLE
Visible property of dragIndicatorArrowNode not maintained in launched sim

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#129]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3.1

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/795 when setting `view.dragIndicatorArrowNode.visibleProperty` to false, it still appears in the launched sim. 

**Steps to reproduce**
In studio, on either screen:
1. Launch all 15 balls 
2. Set `view.dragIndicatorArrowNode.visibleProperty` to false
3. Launch sim

**Visuals**

https://user-images.githubusercontent.com/87318828/162527941-b99e7ced-4df7-407b-a281-b522d1961fec.mp4

**Comment by amanda-phet** [comment]
I'd like to discuss this some more, but not critical for the classroom prototype milestone.

**Comment by KatieWoe** [comment]
This is also the case in the state wrapper

**Comment by samreid** [comment]
Testing in studio master, this seems fixed. @Nancy-Salpepi can you please verify on phettest/master?

**Comment by Nancy-Salpepi** [comment]
@samreid the original problem looks fixed in studio on master on  first 2 screens. I do see some odd behavior with this though. 
If I: 
1. kick 15 balls
2. set view.dragIndicatorArrowNode.visibleProperty to false
3. press Reset All
4. Press Kick 5 
5. set view.dragIndicatorArrowNode.visibleProperty to true --> the arrow appears(usually not over a ball)
6. launch sim --> no arrow is present

If I
1. Refresh Studio
2. Press Kick 5
3. set view.dragIndicatorArrowNode.visibleProperty to true --> the arrow doesn't appear in studio/standard wrapper.

<img width="903" alt="Screenshot 2023-04-25 at 4 29 42 PM" src="https://user-images.githubusercontent.com/87318828/234399265-0302ee98-7368-4e9b-8a8f-e025e408fa27.png">

**Comment by samreid** [comment]
Thanks @Nancy-Salpepi. The commit above solves the problems "launch sim --> no arrow is present" and "the arrow doesn't appear in studio/standard wrapper." There is still an issue that the position at which that indicator shows is independent of the location of the soccer balls. So I'll close this and open a side issue for that aspect.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
