### ISSUE TITLE
Colors for CaV

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/center-and-variability#400]
Just a couple changes to colors in the sim, all of which are on the Variability screen:

- [x] In the Accordion Box, the word, "Range = {{value}}" is currently the same color as the mean. Let's change it to blue: #0000ff 
- [x] Main color for the interval tool handle: intervalToolIconShadedSphereMainColor: #fdf47c
   - I believe this is the only color needed, and scenery does the gradient for the knobs automatically
   - That said, there are two colors that I don't think need to be in the color editor (the current sphere-look gradient is not looking right, and I'm wondering if this is why):
      - intervalToolIconShadedSphereHighlightColor, and 
      - intervalToolIconShadedSphereShadowColor
- [x] intervalToolStroke: #ffed29
- [x] playAreaIntervalToolHandleLineStroke: also #ffed29 to match the stroke color
- [x] pointerColor: #ffdd00

**Comment by samreid** [comment]
I'll work on this

**Comment by samreid** [comment]
Fixed, @catherinecarter can you please review? Close if all is well.

**Comment by catherinecarter** [comment]
I don't know why I suggested blue for the rangeReadout instead of green to match the rectangle. Will you change this to #215E2B, please? Thanks.

Also, the gradient on the sphere still doesn't look right. Comparing the spheres from the predict mean/median with the pointer tool and interval tool spheres, there looks to be a 'shelf' or some sort of exaggerated highlight/lowlight boundary.

<img width="194" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/4844de26-41eb-4bd9-b57b-1b409ba2fe13"> <img width="225" alt="image" src="https://github.com/phetsims/center-and-variability/assets/109630002/897af6db-d641-4a74-bf7c-8e212a83f9b1">

Not sure how to make the spheres look more 'sphere-like,' but I'm hoping we can try.

**Comment by catherinecarter** [comment]
@marlitas and I discussed and noticed this is doing what it's supposed to be doing. No changes needed for the sphere gradient.

Just changing the color of the rangeReadout to be #215E2B is the only thing to do. Thanks!

**Comment by catherinecarter** [comment]
Looks great. Thanks!

**Comment by catherinecarter** [comment]
After seeing @pixelzoom's comment about PhET colors, I'm reopening this issue to change the intervalToolStroke to be PhET yellow: #FEE105
Thanks!

**Comment by samreid** [comment]
Fixed, @catherinecarter want to review? Please close if all is well.

**Comment by catherinecarter** [comment]
All is well. Thank you!
