### ISSUE TITLE
Characters flash when kicking ball using Firefox

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/center-and-variability#91]
**Test device**
Dell

**Operating System**
win10

**Browser**
Firefox

**Problem description**
For https://github.com/phetsims/qa/issues/781:

The kicking movement isn't smooth when the first 5 balls are kicked. It looks like the people are flashing. This seems to only happen with Firefox. 

**Steps to reproduce**
1. On either screen, Press the 'Kick 5' button once--the characters seem to flash a bit.
2. Press the 'Kick 5' button again--the characters move as they should.

**Visuals**

https://user-images.githubusercontent.com/87318828/157882199-fdd75e65-d859-46e6-9cdb-61e4c21bf1d9.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Center and Spread‬
URL: https://phet-dev.colorado.edu/html/center-and-spread/1.0.0-dev.11/phet/center-and-spread_all_phet.html
Version: 1.0.0-dev.11 2022-03-07 01:50:02 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Language: en-US
Window: 1524x910
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by chrisklus** [comment]
@amanda-phet would you like this fixed for the upcoming release? If so, @jonathanolson do you have any ideas what this could be?

**Comment by amanda-phet** [comment]
This should be fixed for 1.0, but not for the classroom prototype milestone.

**Comment by KatieWoe** [comment]
In https://github.com/phetsims/qa/issues/795 it seems like more characters are flashing.
![moreflash](https://user-images.githubusercontent.com/41024075/162481939-eb7ee2bf-3aaa-4245-8d87-40e8f31f269e.gif)

**Comment by samreid** [comment]
This problem is still present and very horrible-looking in Mac/Firefox 112.0.1.

**Comment by samreid** [comment]
This opacity hack looks nice on Firefox:

<details>

```diff

Subject: [PATCH] Export default inline, see https://github.com/phetsims/center-and-variability/issues/149
---
Index: js/common/view/SoccerPlayerNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/SoccerPlayerNode.ts b/js/common/view/SoccerPlayerNode.ts
--- a/js/common/view/SoccerPlayerNode.ts	(revision 223989d731b18badd3dae3f6d387971fa74f3050)
+++ b/js/common/view/SoccerPlayerNode.ts	(date 1682125896659)
@@ -157,16 +157,18 @@
         scale: 13
       } ) );
     }
+    // const SMALL_OPACITY = 0.0001;
+    const SMALL_OPACITY = 1E-16;
 
     soccerPlayer.poseProperty.link( pose => {
-      standingNode.visible = pose === Pose.STANDING;
-      poisedToKickNode.visible = pose === Pose.POISED_TO_KICK;
-      kickingNode.visible = pose === Pose.KICKING;
+      standingNode.opacity = pose === Pose.STANDING ? 1.0 : SMALL_OPACITY;
+      poisedToKickNode.opacity = pose === Pose.POISED_TO_KICK ? 1.0 : SMALL_OPACITY;
+      kickingNode.opacity = pose === Pose.KICKING ? 1.0 : SMALL_OPACITY;
       this.centerBottom = modelViewTransform.modelToViewPosition( new Vector2( 0, 0 ) ).plusXY( -28, 8.5 );
     } );
 
     soccerPlayer.placeInLineProperty.link( placeInLine => {
-      this.visible = placeInLine === 0;
+      this.opacity = placeInLine === 0 ? 1.0 : SMALL_OPACITY;
     } );
 
     const options = optionize<SoccerPlayerNodeOptions, SelfOptions, NodeOptions>()( {


```

</details>

**Comment by samreid** [comment]
Fixed as @jonathanolson prescribed.  Closing.

**Comment by KatieWoe** [comment]
Occurs in https://github.com/phetsims/qa/issues/999

**Comment by marlitas** [comment]
Fixed above. Ready to cherry-pick

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4. Closing.
